openapi: 3.2.0
info:
  title: Prisma Browser Management Console Public Plugins API
  version: 1.0.0
  description: This Open API spec file was created on May 06, 2026. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at [https://www.paloaltonetworks.com/company/trademarks.html](https://www.paloaltonetworks.com/company/trademarks.html). All other marks mentioned herein may be trademarks of their respective companies.
security:
- BearerAuth: []
tags:
- name: Plugins
paths:
  /seb-api/v1/applications/plugins:
    get:
      summary: List all application plugins
      description: Retrieve the plugins details through this Application Programming Interface endpoint.
      operationId: GetSeb-apiV1ApplicationsPlugins
      responses:
        '200':
          description: A list of all application plugin objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PluginResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorResponse:
                    $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
        '500':
          description: Internal server error
      parameters: []
      tags:
      - Plugins
  /seb-api/v1/applications/{id}/plugins:
    get:
      summary: Get a plugin by application ID
      description: Retrieve the plugins details through this Application Programming Interface endpoint.
      operationId: GetSeb-apiV1ApplicationsBy_idPlugins
      responses:
        '200':
          description: A single plugin associated with the application ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PluginResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorResponse:
                    $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
        '404':
          description: Plugin not found
        '500':
          description: Internal server error
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the application to retrieve the plugin for
        schema:
          type: string
      tags:
      - Plugins
    post:
      summary: Create a plugin for an application
      description: Create the plugins details through this Application Programming Interface endpoint.
      operationId: PostSeb-apiV1ApplicationsBy_idPlugins
      responses:
        '201':
          description: Plugin created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  pluginId:
                    type: string
                    description: The ID of the newly created plugin
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorResponse:
                    $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
        '409':
          description: Conflict
        '500':
          description: Internal server error
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the application to create the plugin for
        schema:
          type: string
      tags:
      - Plugins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plugin:
                  $ref: '#/components/schemas/Plugin'
              required:
              - plugin
    put:
      summary: Update a plugin for an application
      description: Update the plugins details through this Application Programming Interface endpoint.
      operationId: PutSeb-apiV1ApplicationsBy_idPlugins
      responses:
        '200':
          description: Plugin updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  pluginId:
                    type: string
                    description: The ID of the updated plugin
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorResponse:
                    $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
        '404':
          description: Plugin not found
        '500':
          description: Internal server error
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the application to update the plugin for
        schema:
          type: string
      tags:
      - Plugins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plugin:
                  $ref: '#/components/schemas/Plugin'
              required:
              - plugin
    delete:
      summary: Delete a plugin for an application
      description: Delete the plugins details through this Application Programming Interface endpoint.
      operationId: DeleteSeb-apiV1ApplicationsBy_idPlugins
      responses:
        '200':
          description: Plugin deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  pluginId:
                    type: string
                    description: The ID of the deleted plugin
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorResponse:
                    $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
        '404':
          description: User group not found
        '500':
          description: Internal server error
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the application associated with the plugin to delete
        schema:
          type: string
      tags:
      - Plugins
components:
  schemas:
    Plugin:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/PluginEvent'
        links:
          type: array
          items:
            $ref: '#/components/schemas/PluginLink'
        elements:
          type: array
          items:
            $ref: '#/components/schemas/PluginElement'
    PluginEvent:
      type: object
      properties:
        eventType:
          type: string
          enum:
          - loginFail
          - loginAttempt
          - passwordReset
          - userRegistration
        requestUrl:
          type: string
        triggerUrl:
          type: string
        triggerOnSuccess:
          type: boolean
        triggerOnFail:
          type: boolean
        method:
          type: string
          enum:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
        statusCode:
          type: integer
        minContentLength:
          type: integer
        maxContentLength:
          type: integer
        headers:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              content:
                type: string
            required:
            - name
            - content
      required:
      - eventType
    PluginElement:
      type: object
      properties:
        elementType:
          type: string
          enum:
          - excludeAccountShield
          - includeAccountShield
        urlPattern:
          type: string
        selectors:
          type: array
          items:
            type: string
      required:
      - elementType
      - selectors
    ErrorResponse:
      type: object
      required:
      - message
      properties:
        error:
          type: string
        message:
          type: string
        missingDeviceIds:
          type: array
          items:
            type: string
          description: List of device IDs that were not found (only present for device not found errors)
        missingUserIds:
          type: array
          items:
            type: string
          description: List of user IDs that were not found (only present for user not found errors)
    PluginLink:
      type: object
      properties:
        urlPattern:
          type: string
        resetPasswordUrl:
          type: string
        loginPageUrl:
          type: string
    PluginResponse:
      type: object
      properties:
        id:
          type: string
          format: string
          description: Unique identifier
        createTime:
          type: string
          format: date-time
          description: Creation time of the plugin
        updateTime:
          type: string
          format: date-time
          description: Last update time of the plugin
        plugin:
          $ref: '#/components/schemas/Plugin'
        applicationId:
          type: string
          description: Application ID of the application the plugin is associated to
      required:
      - id
      - createTime
      - updateTime
      - plugin
      - applicationId
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your JWT Bearer token to authorize.
