openapi: 3.2.0
info:
  title: Prisma Browser Management Console Public User Requests API
  version: 1.0.0
  description: This Open API spec file was created on May 06, 2026. © 2026 Palo Alto Networks, Inc. Palo Alto Networks is a registered trademark of Palo Alto Networks. A list of our trademarks can be found at [https://www.paloaltonetworks.com/company/trademarks.html](https://www.paloaltonetworks.com/company/trademarks.html). All other marks mentioned herein may be trademarks of their respective companies.
security:
- BearerAuth: []
tags:
- name: User Requests
paths:
  /seb-api/v1/user-requests:
    get:
      summary: Returns a list of user requests
      description: Retrieve the user requests details through this Application Programming Interface endpoint.
      operationId: GetSeb-apiV1User-requests
      responses:
        '200':
          description: A list of requests with pagination info
          content:
            application/json:
              schema:
                type: object
                properties:
                  pageInfo:
                    $ref: '#/components/schemas/PageInfo'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserRequest'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      parameters:
      - name: limit
        in: query
        description: Number of user requests to return
        required: false
        schema:
          type: integer
          format: int32
      - name: request.type
        in: query
        description: Filter by request type
        required: false
        schema:
          type: string
          enum:
          - WebAccess
          - AppLogin
      - name: request.user_id
        in: query
        description: Filter by request user id
        required: false
        schema:
          type: string
      - name: request.device_id
        in: query
        description: Filter by request device id
        required: false
        schema:
          type: string
      - name: request.rule_id
        in: query
        description: Filter by request rule id
        required: false
        schema:
          type: string
      - name: request.url
        in: query
        description: Filter by request url
        required: false
        schema:
          type: string
      - name: request.responded_by
        in: query
        description: Filter by response by user id
        required: false
        schema:
          type: string
      - name: request.status
        in: query
        description: Filter by request status
        required: false
        schema:
          type: string
          enum:
          - Approved
          - Declined
          - Pending
          - Revoked
      - name: cursor
        in: query
        description: An optional opaque string that defines from where to start listing
        required: false
        schema:
          type: string
      - name: sort
        in: query
        description: The field to sort by
        required: false
        schema:
          type: string
          enum:
          - request.created_at
          - request.type
          - request.status
          - request.response_time
          - request.url
      - name: order
        in: query
        description: The sort order
        required: false
        schema:
          $ref: '#/components/schemas/Order'
      tags:
      - User Requests
  /seb-api/v1/user-requests/{id}:
    get:
      summary: Returns a request by ID
      description: Retrieve the {id} details through this Application Programming Interface endpoint.
      operationId: GetSeb-apiV1User-requestsbyid
      responses:
        '200':
          description: A request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRequest'
        '404':
          description: Request not found
      parameters:
      - name: id
        in: path
        description: Request ID
        required: true
        schema:
          type: string
      tags:
      - User Requests
  /seb-api/v1/user-requests/{id}/action:
    post:
      summary: Act upon a user request
      description: Create the action details through this Application Programming Interface endpoint.
      operationId: PostSeb-apiV1User-requestsBy_idAction
      responses:
        '200':
          description: Action performed on request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRequest'
        '404':
          description: Request not found
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
        '500':
          description: Internal server error
      parameters:
      - name: id
        in: path
        description: Request ID
        required: true
        schema:
          type: string
      tags:
      - User Requests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAction'
  /seb-api/v1/user-requests/{id}/revoke:
    post:
      summary: Revoke already approved request
      description: Create the revoke details through this Application Programming Interface endpoint.
      operationId: PostSeb-apiV1User-requestsBy_idRevoke
      responses:
        '200':
          description: Action performed on request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRequest'
        '404':
          description: Request not found
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
        '500':
          description: Internal server error
      parameters:
      - name: id
        in: path
        description: Request ID
        required: true
        schema:
          type: string
      tags:
      - User Requests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokeRequestAction'
components:
  schemas:
    RequestAction:
      type: object
      properties:
        action:
          type: string
          enum:
          - approve
          - decline
          description: Action to perform on the request
        adminComment:
          type: string
          format: string
          description: Admin comment on the action
        adminBypassTimeframe:
          type: string
          enum:
          - Once
          - 10m
          - 1h
          - 4h
          - 9h
          - 12h
          - 24h
          - 3d
          - 7d
          - 14d
          - 30d
          - 60d
          - 90d
          description: The timeframe for which the approval is valid
      required:
      - action
    RequestError:
      type: object
      properties:
        error_message:
          type: string
    RevokeRequestAction:
      type: object
      properties:
        revokerComment:
          type: string
          format: string
          description: Admin revoke comment
      required:
      - action
    UserRequest:
      type: object
      properties:
        id:
          type: string
          format: string
          description: Unique identifier
        userId:
          type: string
          format: string
          description: Request unique identifier
        type:
          type: string
          format: string
          description: Request type
        status:
          type: string
          format: string
          description: Request status
        url:
          type: string
          format: string
          description: bypassing url
        reason:
          type: string
          format: string
          description: reason for request
        deviceId:
          type: string
          format: string
          description: Device unique identifier
        ruleId:
          type: string
          format: string
          description: Blocking rule unique identifier
        adminComment:
          type: string
          format: string
          description: Admin comment
        createdAt:
          type: string
          format: date-time
          description: Request created at
        userAcceptedAt:
          type: string
          format: date-time
          description: User accepted response at
        responseTime:
          type: string
          format: date-time
          description: Admin response time
        adminBypassTimeframe:
          type: integer
          format: string
          description: The timeframe for which the approval is valid
        respondedBy:
          type: string
          format: string
          description: Response by
        revokedBy:
          type: string
          format: string
          description: Revoked by
        revokedAt:
          type: string
          format: date-time
          description: Admin revoke time
        revokerComment:
          type: string
          format: string
          description: Revoke comment
      required:
      - id
      - userId
      - status
      - type
      - url
      - reason
      - ruleId
      - createdAt
      - deviceId
    Order:
      type: string
      description: The sort order
      enum:
      - asc
      - desc
    PageInfo:
      type: object
      properties:
        hasNextPage:
          type: boolean
          description: When paginating forwards, are there more items?
        cursor:
          type:
          - string
          - 'null'
          description: When paginating forwards, the cursor to continue.
      required:
      - hasNextPage
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your JWT Bearer token to authorize.
